### ISSUE TITLE
Add OpenFGA to https://github.com/cncf/contribute

### ISSUE THREAD

**Issue by aaguiarz** [openfga/community#34]
Relates to https://github.com/cncf/toc/issues/921

**Comment by aaguiarz** [comment]
Create a PR here https://github.com/cncf/tag-contributor-strategy

**Comment by rhamzeh** [comment]
I think those changes will be automatically synced from landscape, which we already did.

Based on the comments here: https://github.com/cncf/tag-contributor-strategy/pull/222#issuecomment-1234936206

> I think we now have a bot that syncs this repository with the landscape, and we don't require manual edits to this projects.json file anymore. [...]

> Correct. So there's no point in merging this PR as the projects.json file will be overwritten. Just update the data in landscape. I wonder if we need to document that somewhere to make it clear?

**Comment by aaguiarz** [comment]
Yep, however, I changed the description in landscape and it did not synchronize. The logo did.
