### ISSUE TITLE
Add projects@cncf.io to Web Analytics for openfga.dev

### ISSUE THREAD

**Issue by aaguiarz** [openfga/community#40]
https://github.com/cncf/toc/issues/921

**Comment by aaguiarz** [comment]
@rhamzeh is this something you can help with? Do we have our own analytics account?

**Comment by rhamzeh** [comment]
We do not have analytics beyond the anonymized ones provided by Cloudflare.

We do need to transfer the domain I assume? If we are transferring to Cloudflare, we have to re-setup analytics there, other registrars don't have that ability.

Are we required to setup analytics? If so, any preferred vendors?

**Comment by aaguiarz** [comment]
We'll need to transfer the domain too.

If we don't have analytics let's close this one for now.
